site_name:        ChainMap.jl
repo_url:         https://github.com/bramtayl/ChainMap.jl
site_description: Integrates chaining and mapping
site_author:      Brandon Taylor

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math

docs_dir: 'build'

pages:
  - Home: index.md
  - Exports: docstrings.md
